name: melamp
recipe: lamp
config:
  webroot: .
  php: 5.6
  database: mariadb:10.3

# This is important because it lets lando know to test against the plugin in this repo
# DO NOT REMOVE THIS!
plugins:
  "@lando/lamp": ./../../