name: LAMP Tests

on:
  pull_request:

jobs:
  leia-tests:
    runs-on: ${{ matrix.os }}
    env:
      TERM: xterm
    strategy:
      fail-fast: false
      matrix:
        lando-version:
          - 3-edge
        os:
          - ubuntu-24.04
        node-version:
          - '20'
        leia-test:
          - examples/lamp-init
          # - examples/lamp-custom
          # - examples/lamp-defaults
          # - examples/lamp-downstreamer-1
          # - examples/lamp-downstreamer-2
          # - examples/lamp-export
          # - examples/lamp-import
          # - examples/lamp-mariadb
          # - examples/lamp-mariadb-mysql
          # - examples/lamp-mysql8
          # - examples/lamp-nginx

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install node ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install NPM dependencies
        run: npm clean-install --production --prefer-offline --frozen-lockfile
      - name: Bundle Deps
        uses: lando/prepare-release-action@v3
        with:
          lando-plugin: true
          version: dev
          sync: false
      - name: Setup lando ${{ matrix.lando-version }}
        uses: lando/setup-lando@v3
        with:
          lando-version: ${{ matrix.lando-version }}
          config: |
            setup.skipCommonPlugins=true
            setup.plugins.@lando/lamp=/home/runner/work/lamp/lamp
          telemetry: false
      - name: DEBUG
        run: |
          cd examples/lamp-init
          rm -rf lamp && mkdir -p lamp && cd lamp
          lando init --source remote --remote-url https://github.com/bcit-ci/CodeIgniter/archive/3.1.13.tar.gz --remote-options="--strip-components 1" --recipe lamp --webroot . --name lando-lamp --option composer_version=1.10.1 --debug

      # - name: Run Leia Tests
      #   uses: lando/run-leia-action@v2
      #   with:
      #     leia-test: "./${{ matrix.leia-test }}/README.md"
      #     cleanup-header: "Destroy tests"
      #     shell: bash
      #     stdin: true
